### ISSUE TITLE
Fix broken links for input/output formats in data file

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Project-Explorer#16]
Some projects contained links in the `input`/`output` fields, pointing to sites where the supported file formats had been listed. These have been broken during the conversion, and resulted in things like

    "inputs" : [ "[Multiple](https:", "", "blackthread.io", "gltf-converter", "#supported-formats)" ],

(see https://github.com/KhronosGroup/glTF-Project-Explorer/blob/master/public/data/glTF-projects-data.json#L1225 )

Assuming that `input`/`output` should *not* contain markdown, these links should be fixed, and where applicable, the link should be added to the `description`.

<sup>(I'll tackle this ASAP, this issue is rather a reminder)</sub>

**Comment by javagl** [comment]
@weegeekps The `input`/`output` fields should probably at least state the glTF version. But thinking about this, the string `Multiple` may not be so sensible: When someone is looking for a converter from `FBX` to `glTF 2.0`, it will not be found...

Maybe there should be some sort of wildcard, e.g. using `"*"` to indicate multiple formats? (I'd have to take a closer look at how something like this could be aligned with the current implementation of the search+filter functionality...)

Do you have an idea what could be the best approach here?

**Comment by weegeekps** [comment]
If we can, I think the best approach would be to explicitly list out the file formats since the field supports a list of strings. This should allow us to add filters for both the Input and Output methods in the future. I've noticed some other places where we can do this separation, for example **FBX2gltf (ClayGL)**, where we currently have a string with multiple comma separated values.

```json
"inputs" : [ "FBX, COLLADA, OBJ" ],
```

In this case, we show only one entry and using our existing filtering logic, we'd have "FBX, COLLADA, OBJ" filter tag created at init. Breaking these out into individual options allows better tags to be created.

```json
"inputs" : [ "FBX", "COLLADA", "OBJ" ],
```

Now we have 3 tags created for the Input Methods field, so users could filter on any one of these and get the results they expect. Using the Blackthread.io example from https://github.com/KhronosGroup/glTF-Project-Explorer/blob/master/public/data/glTF-projects-data.json#L1225, we'd list out the list similar to this:

```json
"inputs": [ "3MF", "AMF", "FBX", "OBJ", "glTF 2.0", "glTF 1.0", "COLLADA", "Three.js JSON format", "PCD", "PLY", "STL" ],
"outputs": [ "glTF 2.0" ]
```

That said, we have 45 entries of "Multiple" at the moment, and only about eight of these have links. I think maybe you and I following the links that are provided and listing out the formats and then leaving "Multiple" where we don't have a good link is a decent start. When we broadcast the existence of this tool, we may want to also ask maintainers of the projects listed by us to at least drop by and update their entries, and explicitly provide guidance asking them to flesh out their list of inputs and outputs.

**Comment by javagl** [comment]
The fact that some strings had `"Not, been, split"` could be considered a bug in my initial conversion process. Generally, they should all have been stored as arrays of strings.

---

I went through the data file (no PR yet), and the result of the first pass is at https://github.com/javagl/glTF-Project-Explorer/commit/f53c3eec184eb68e042b6dcd73043527f7b7bf11

- Split `inputs`/`outputs` strings:
    - things like `"OBJ, FBX"` into `"OBJ", "FBX"`
    - `"glTF 1.0 and 2.0"` into `"glTF 1.0", "glTF 2.0"`
    - `"Multiple, glTF 2.0"` into `"Multiple", "glTF 2.0"`
- Fixed broken links for formats that had been behind `"Multiple"`
- Replaced some `"Multiple"` entries with lists of file extensions

In some cases, I did not list the supported file formats, but kept the `"Multiple"` entry, because the information was hard to find, or too long and detailed. The latter refers to cases where the website mentions file format version numbers, or claims a "partial" support, sometimes even mentioning the supported features. (I added links in the description in some cases, but not systematically...)

Many entries had `"?"` listed as their supported formats. This has mostly been the case for plugins for applications like Maya/Cinema4D/...etc. I replaced the `"?"` with `"Multiple"` in these cases, because the file formats will there generally be "all that the application supports". 
I'm not sure what's the best solution here. We could gather the supported formats for the "large 3D applications" at some point, and then Copy+Paste them for the importer plugins. Alternatively, we could say that it is an importer/exporter for *glTF 2.0*, regardless of which formats the application supports. But then, people might not find the plugin when looking for a way to convert their models.

Another question is whether we should differentiate between `glTF` and `GLB` somehow. (`GLB` is sometimes listed explicitly, but usually not...)

---

Minor other things:

- Fixed some input/output mixups
- Removed duplicate entry for blackthread.io
- Simplygon Cloud seems to no longer exist - should it be removed?


---

Should I create a PR for that already, so that we can tackle the questions mentioned above in another pass?

**Comment by weegeekps** [comment]
Yeah, I'd say lets go ahead and create another PR. Couple thoughts:

Once the announcement goes out, we may have some decent success reaching out the the glTF community at-large and asking them to come update their entries. My hope is that would do a decent job at cleaning up those `"Multiple"` entries. At least far better than we can do ourselves.

Re: `glTF` and `GLB`, I'm torn. I think there's a fair argument to be made that `GLB` is `glTF` but it's definitely true that not all tools out there support both. This may be an ask to bring up to the wider group on the weekly call.

**Comment by javagl** [comment]
This somehow got buried. The changes done in https://github.com/javagl/glTF-Project-Explorer/commit/f53c3eec184eb68e042b6dcd73043527f7b7bf11 *seem* to basically made their way into the data file (although admittedly, I couldn't find "the" commit where they have been added in the "blame" view).

I'll open another issue for the specific point of `glTF` vs. `GLB`
