### ISSUE TITLE
Travis/npm build issues; main/live site not up-to-date

### ISSUE THREAD

**Issue by jbherdman** [KhronosGroup/glTF-Project-Explorer#161]
Recent main-branch changes have not been deployed to the version at https://github.khronos.org/glTF-Project-Explorer/.

As seen here, the last few "Travis CI builds", over the past 2 months or so, have not succeeded:
https://app.travis-ci.com/github/KhronosGroup/glTF-Project-Explorer/builds

I assume that is the reason why the main "live site" does not have the latest data-changes.

**Comment by javagl** [comment]
Thanks for pointing that out (I definitely should have noticed that earlier!)

I tried a fix at https://github.com/KhronosGroup/glTF-Project-Explorer/pull/162 , but would like to treat the build system as a black-box here, so if someone could review this, that would be great.

**Comment by javagl** [comment]
(An aside, @weegeekps : Maybe we should conver this to GitHub actions at some point)

**Comment by javagl** [comment]
@weegeekps The PR seems to have fixed the build, but the deployment errored at https://app.travis-ci.com/github/KhronosGroup/glTF-Project-Explorer/builds/259936736 . Unless you already know what this is about, I'd have a closer look at that soon.

**Comment by weegeekps** [comment]
@javagl Looks like our credentials have gone bad. @outofcontrol we may need your help here.

**Comment by outofcontrol** [comment]
Most likely fallout from the tokens being leaked a few weeks ago.

**Comment by weegeekps** [comment]
That makes a lot of sense. I legitimately thought we had already migrated this to GitHub Actions so I didn't pay much attention to the Travis stuff going on.

I can't get it done tonight, but I will move us over to GitHub actions tomorrow. That seems like the better solution rather than getting a new token for Travis when we are already planning on moving away from it. I have a recipe put together for another similar site of mine so it won't take long for me to convert.

**Comment by outofcontrol** [comment]
Thank you @weegeekps You saved me trying to find my notes which account I set it up in :)

**Comment by jbherdman** [comment]
I see that this was potentially resolved via the changes in #164.

However, the live/deployed site is still missing the changes from #160 (as well as #158 and #157).

**Comment by javagl** [comment]
Indeed, the "Deploy" step is grayed out in https://github.com/KhronosGroup/glTF-Project-Explorer/actions/runs/4211871861/jobs/7310498444 

Looking at the line that says
```
 if: ${{ github.ref == 'refs/head/main' }}
```
in https://github.com/KhronosGroup/glTF-Project-Explorer/blob/c90881bf10f6fef2805098f2da4175ed35464056/.github/workflows/ci.yaml#L31 and comparing it to the examples at https://github.com/peaceiris/actions-gh-pages#getting-started , I think that it should be
```
 if: ${{ github.ref == 'refs/heads/main' }}
```
@weegeekps If you know for sure, drop me a note. Otherwise... I might as well just try it out. What should happen, except for the build not being deployed 😁

**Comment by javagl** [comment]
The linked PR seems to fix it 
<sup>(and I'll forever bite my ... self for the typo)</sup>

The "Deploy" step in https://github.com/KhronosGroup/glTF-Project-Explorer/actions/runs/4439173209/jobs/7791283653 has run, and the new entries/updates from #157, #158, and #160 are now visible on https://github.khronos.org/glTF-Project-Explorer/ 

Thanks @jbherdman for pointing that out!

(I assume that it is OK to close this one now - feel free to reopen when there's still any issue)
