### ISSUE TITLE
Sort order of entries in data file

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Project-Explorer#23]
This is rather a discussion point, and a somewhat difficult one...

Currently, there are some odd entries are at the top of the JSON data file - e.g. entries for glTF support in some browsers, which eventually have not really been implemented...

<sup>Yes, that's my fault - I just added the entries in the order in which they appeared at that point in the "Late Breaking" list...</sup>

Some questions that we might have to think about:

- Should we edit the data file to move the "odd" entries to the bottom? 
- More generally: Should we apply some arbitrary order to the other projects, based on a vague gut feeling (a mix of subjective "importance", "activity", "maturity"...?)
- Project authors who submit their project via PRs may (likely) try to add their projects prominently at the top...

For example, I'd rather like to see things like the glTF validator at the top when opening the project explorer, because it is an important *and* unique Khronos-owned project. Similarly, for the Khronos-owned converters or the reference viewer. But beyond that, I'd hesitate to dictate any sort order...

I think during the calls, we also considered some sort of "featuring/starring" for recommended projects, but we haven't really thought about an approach for this.

**Comment by javagl** [comment]
Considerations from the call:

- Alphabetical order would be the most fair solution
- Having a flag indicating the official Khronos projects?
  - Maybe even display them as an own category?
- More generally: Any sort of priorization for the projects?
- Having a server pull the "number of stars" for GitHub projects to use this as a sort order?
  - This could be a script that runs once per week - *not* for each request by clients
- Are all resources really on GitHub? 
  - Not all: Some proprietary applications or model repositories, but most applications/libraries are on GitHub
- Suggestion: Two flags: Khronos (yes/no) and "Staff Pick" (yes/no) to use as primary order, and alphabetical order as secondary

**Comment by weegeekps** [comment]
So, I ran out of time today to actually fully implement this, but here's what I'm planning. I will try to wrap it up tomorrow or Friday. Now that I'm also feeling healthy again, I may try to do some additional work on Saturday as well.

For the Khronos official project flag, I'm going to key the boolean field `khronosOfficial`. For the Staff Pick, I'm thinking of going with a `staffPick` boolean field. In both cases I'm using _camelCase_ just because it's easier to deal with in the browser JSON parsers and follows general industry standards for TypeScript/JavaScript.

On the UI side, I am going to add two "switch" elements that users can use to filter against these two new fields. Additionally, I'm going to make the "on" state of these switch elements exclusive; if you're filtering by "Khronos Official", you can't also choose "Staff Picks". Implementing the switch element is where I left off this evening.

@pjcozzi and @javagl, do we have an idea what we'd like to flag initially as "Staff Picks"?

Additionally, I'm going to configure the sorting to follow the pattern discussed, with the Khronos Official projects by alpha at top, then the Staff Picks by alpha, then the rest by alpha. For testing, I am going to flag Three.js and Babylon as Staff Picks so we at least have some content there until others can get back to me.

**Comment by javagl** [comment]
When it comes to questions like this, I'm always trying to extrapolate possible future demands and see whether they can be handled more generically. **Very** roughly speaking: When there are *two* possible flags, might there be a third one in the future? If so, shouldn't this be handled with something like a `"tags" : [ "khronosOfficial", "staffPick", ... ]` property? 

<sub>On a *far* more technical level, and assuming that there will be several different sorting criteria and priorizations: How can this be structured in order to easily configure the sort order? But I'm not familiar enough with React/TypeScript/... to even *guess* what might be the best solution here - Pseudocode would involve lines like `this.sorter = Sorters.createAlphabeticalWithPriorizedTags("khronosOfficial");` or so...</sub>

On the one hand, the issue about the boolean fields is critical: The current "schema" will eventually have to be cast into some sort of database schema, and preferably, there should *very* rarely be a reason to change this and migrate it to a different schema. On the other hand, we currently only have the JSON file, and thus, some leeway to try out what works best, and hopefully pick the right approach when this goes into a live database.

**Comment by weegeekps** [comment]
I rather like the "tags" approach. It fits with the rest of patterns we're already using and instead of using a switch we can add another filter element. I think I might start going back in that direction.

There are a lot of different approaches we can take here, but for the first pass I am likely going to add a step within `store/results/Sagas.ts:*applyFIlters()` to take the filtered results and sort them. My first pass is just going to provide a static list of tags to prioritize in priority form. Then I'm going to split the filtered results into buckets, sort each bucket by alpha in parallel, and then join everything together based on the said priority. Hard to describe but should work well for us for now.

When we move to having a backing database, I think the best approach is to still just spit out the data in a format similar to our JSON file. As long as it's not an unreasonably large output, continuing to perform filtering and searching on the client side generally performs better at the cost of upfront loading time. If we continue with a client-side approach, having the extra flexibility provided by a "tags" field won't significantly harm us and actually may make managing the database easier in the future. If we have a new boolean tag to add, we can just add it without having to modify the database.

**Comment by javagl** [comment]
Fixed via https://github.com/KhronosGroup/glTF-Project-Explorer/pull/24
