### ISSUE TITLE
Tracking a backlog of projects to add to glTF Explorer

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Project-Explorer#78]
@javagl @weegeekps 

I appreciate the instructions in the README on how to add a new glTF project to Project Explorer:

> In order to add your project to the project list, you can fork this repository, add your project information to the glTF-projects-data.json file, and submit a pull request with the changes. Alternatively, you can also open an issue that contains the relevant project information as described below.

I often run into new (or new to me) glTF adoptions in the wild (like this https://www.youtube.com/watch?v=MoYshrfCkNw&t=19s) but I rarely have the time to fully research it and open a pull request.

Is it possible for us to start/re-start a lightweight way to track a backlog of projects to add?

When we were just using the glTF GitHub repo's README.md to track the ecosystem, we used a GitHub issue to track the backlog: https://github.com/KhronosGroup/glTF/issues/1058

Perhaps we should continue with that issue (and also go through it for new projects to add here) or start a new issue in this GitHub repo?

Open to any and all ideas.  I feel like the ecosystem is growing much faster than we are tracking.  Good problem, but a lightweight way to backlog would be game changing.

**Comment by javagl** [comment]
The statement from the README to...

> open an issue that contains the relevant project information

... can be seen as the second-most desirable approach (after opending a PR with the full `data.json` update). But there's also the option to just open an issue here, like

> **Add animech Unreal4Web**
> 
> Add https://www.youtube.com/watch?v=MoYshrfCkNw&t=19s (or https://animech.com/en/unreal4web-2/ ) to the list
>

and ... \*ehrm\* ... "someone" will then certainly (try to) take care of that. Actually, *most* of the current entries have originally been created from short pointers in the famous "Late-Breaking" issue, so that could be a viable approach.

I'd probably prefer to have *individual* issues for the things that should be added. This would make maintenance easier: The issue could just be closed after it has been integrated. Also, the single issue could be used to track additional information that may be integrated, *before* the entry is actually added to the `data.json`.  If the project is an open-source project, one could open an issue *there*, pointing to the issue *here*, as a "heads up" for the developers. 

Of course, depending on the desired level of detail and the type of the project, and the amount of details that are freely available, it could sometimes make sense to reach out to the respective company and ask them about all that. But that's where a certain trade-off comes into play, in terms of the time that a volunteer has to invest to ... essentially do some "avertising" for the respective company...

**Comment by pjcozzi** [comment]
> I'd probably prefer to have individual issues for the things that should be added

@javagl sounds good for to me.  I'll run with this as I come across new projects in my travels unless anyone suggests otherwises.

Perhaps see how things unfold but it may also be useful to make a few different GitHub labels for `new project`, `needs more info`, or whatever else could be a helpful workflow.

**Comment by weegeekps** [comment]
+1 for adding individual issues.

We could have a prepared issue template that has some quick instructions with a "form" (I use that term lightly) where people can add the data they have on hand. Something like:

```
Title: Joe's Cool glTF Viewer
Description: Views glTF files and was written by Joe.
URLs: http://www.example.com/ https://www.example.com/
...etc
```

With instructions to attach the "New Project" label. Then we can decide if it needs more info and follow up with the submitter, or do the digging on our own if it seems obvious.

I can take some time in the next week or so to put together a template unless @javagl wants to do so. Either way is fine with me.

**Comment by pjcozzi** [comment]
@weegeekps LOVE the issue template idea.

> With instructions to attach the "New Project" label.

Note that GitHub issue templates allow you to assign an initial label or labels.

**Comment by javagl** [comment]
I'm old-school enough to consider the example JSON in the README as a "template" :-) Until now, *most* additions to the list had been via 'Late Breaking' pointers, or via PRs - but adding a GitHub issue template could have a good effort-to-helpfulness ratio, so that's certainly a sensible thing to do.

**Comment by javagl** [comment]
The submission of new projects is now simplified via the WordPress submit form, as stated in the main README.

There is still the option to just open a new issue here, with a link and a comment saying "There's a new project", and ... someone ... will then fill out the WordPress form with the relevant information. (The "Late-breaking" approach 😁 )
